### ISSUE TITLE
jscore 

### ISSUE THREAD

**Issue by evanrootrisksense** [endobson/racket-webkit#1]
I'm a dumb novice, but in the hope that I'm right, is this supposed to work with 'just $racket example.rkt'? because I get an error on jscore not being in the collections. I then thought maybe moving jscore into my collections path would work but it didn't, and now I think I'm nieve for thinking that I could clone racket code and just execute it. 

Pointers? 

Full Error text on my Win10 system. 
```
C:\Users\eroot\Documents\Racket\racket-webkit-master>racket examples.rkt
jscore\ffi.rkt:7:1: collection not found
  for module path: unstable/contract
  collection: "unstable"
  in collection directories:
   C:\Users\eroot\AppData\Roaming\Racket\6.6\collects
   C:\Program Files\Racket\collects
   ... [162 additional linked and package directories]

C:\Users\eroot\Documents\Racket\racket-webkit-master>

```

**Comment by endobson** [comment]
That error is saying that unstable/contract is not in your collection path, the jscore module is found but it is the one that has the issue. This code is over 5 years old and looks like it has bitrotted and no longer works on the latest Racket distribution, you can probably remove the require and figure out what I was using that was in unstable and then replace it/remove it. I'm not maintaining this code as it was just an example I got working to see what was possible, so no guarantees that it works with the latest WebKit. Also I only tested it on OS X as that is my OS, so likely it will have issues on Windows.
